# Generated by Django 4.2.3 on 2023-07-22 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("car_app", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("posting_date", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="car_app.car"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        default="profiles/default_profile_photo.jpg",
                        null=True,
                        upload_to="profiles/",
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("addr_1", models.CharField(blank=True, max_length=100, null=True)),
                ("addr_2", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[("MH", "Maharashtra"), ("GJ", "Gujarat")],
                        null=True,
                    ),
                ),
                ("zip_code", models.CharField(blank=True, max_length=6, null=True)),
                ("country", models.CharField(default="India", editable=False)),
                ("contact", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("Staff", "Staff"), ("Customer", "Customer")],
                        default="Customer",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
