# Generated by Django 4.2.3 on 2023-07-22 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("manufacturer_name", models.CharField(max_length=200, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("posting_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("model_name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("posting_date", models.DateTimeField(auto_now_add=True)),
                (
                    "manufacturer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="car_app.manufacturer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title_status", models.CharField(max_length=20)),
                ("build_year", models.IntegerField()),
                ("car_condition", models.CharField(max_length=50)),
                ("cylinders", models.IntegerField()),
                ("fuel", models.CharField(max_length=20)),
                ("odometer", models.IntegerField()),
                ("transmission", models.CharField(max_length=20)),
                ("vin", models.CharField(max_length=30)),
                ("drive", models.CharField(max_length=50)),
                ("car_size", models.CharField(max_length=50)),
                ("car_type", models.CharField(max_length=50)),
                ("paint_color", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=300)),
                ("state", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("sold_out", models.BooleanField(default=False)),
                ("selling_price", models.IntegerField()),
                ("posting_date", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="car_app.manufacturer",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="car_app.model"
                    ),
                ),
                (
                    "purchased_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
