# Generated by Django 4.2.3 on 2023-07-22 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("car_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="purchased_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_id",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
